version: 2
updates:
  - package-ecosystem: npm
    directory: '/packages/**'
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    versioning-strategy: increase
    labels:
      - 'pr: dependencies'
