FROM tiangolo/uwsgi-nginx-flask:python3.9

RUN pip install --upgrade pip

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app

ENV FLASK_APP=manage.py
ENV FLASK_DEBUG=1
ENV DATABASE=rawbase.db

RUN pip install --no-cache-dir pipenv
RUN pipenv shell
RUN pipenv install -r requirements.txt

EXPOSE 3006

COPY . .

CMD ["flask", "run", "--host=0.0.0.0", "--port=3006"]